apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/the-overheard-club/overheardgateway
      context: ../overheard-gateway
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
