apiVersion: v1
kind: Service
metadata:
  name: overheardgateway
  namespace: default
  labels:
    app: overheardgateway
spec:
  selector:
    app: overheardgateway
  type: LoadBalancer
  ports:
    - name: http
      port: 8076
